services:
  # React Frontend
  - type: web
    name: defi-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Express API Server
  - type: web
    name: defi-api-server
    env: node
    buildCommand: npm install
    startCommand: npm run admin
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Telegram Bot
  - type: worker
    name: defi-telegram-bot
    env: node
    buildCommand: cd telegram-bot && npm install
    startCommand: cd telegram-bot && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
